name: Build and run tests

on:
  push:
    branches: [ main, staging, dev ]
  pull_request:
    branches: [ main, staging, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.1
        cache: 'npm'
    - run: npm i
    # - run: npm test

  deploy_dev:
    if: contains( github.ref, 'staging')
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        HOSTNAME : ${{ secrets.HOSTNAME  }}
        USER_NAME : ${{ secrets.USER_NAME  }}
    steps:
      - run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} uptime
      - run: |
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
          . ~/.nvm/nvm.sh &&
          cd /var/www/ultimo-front &&
          git pull origin staging &&
          npm i &&
          pm2 delete bdv-app &&
          pm2 start npm --name "bdv-app" -- start
          '
